site_name: How to use myBCIT
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.links
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode
      primary: indigo
      accent: yellow
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to Light Mode
      primary: indigo
      accent: yellow

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/TatsunoriMarumo/HowToUseMyBCIT

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: 
  &copy 2024 <a href="https://github.com/Momona-Wada" target="_blank" rel="noopener">Momona Wada</a>, and <a href="https://github.com/TatsunoriMarumo" target="_blank" rel="noopener">Tatsunori Marumo</a>
