site_name: How to use myBCIT
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.links
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to Light Mode
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/TatsunoriMarumo/HowToUseMyBCIT

copyright: 
  &copy 2024 <a href="https://github.com/Momona-Wada" target="_blank" rel="noopner">Momona Wada</a>, and <a href="https://github.com/TatsunoriMarumo" target="_blank" rel="noopner">Tatsunori Marumo</a>